import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import getMenuItems from "@/functions/getMenuItems";
import { fetchPageData } from "@/functions/getPageData";
import { getLanguageLinks } from "@/functions/getLanguageLinks";
import vars from "@/vars/vars";
import { readFromUrl } from "@/functions/nieuzywane/readFromUrl";
import { SwitchLanguageType } from "@/types/types";
import { RoutingConfig } from "@/middleware";
// import { fetchLocales } from "@/components/lib/fetchLocales";
import { getCachedLocales } from "@/functions/nieuzywane/storage/storedCache";
import { headers } from "next/headers";
// import { getLocales } from "@/components/lib/localesStore";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "This is Page. The - Page.",
  description: "Generated by create next app",
};

export default async function WebLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ web?: string[],
    lang: string
   }>;
}>) {

 const { web, lang } = await params;


   const pageSlug = web?.join('/') ?? 'home';
// const rfurl = readFromUrl(web, lang);
// const fullPath = `${lang}/${contentSlug}`;

const [urlItems,contentData] = await Promise.all([
//  getMenuItems(rfurl.pageLocale),
//  fetchPageData(rfurl.pageSlug, rfurl.pageLocale)
getMenuItems(lang),
 fetchPageData(pageSlug, lang)
]);
const urlItemsInsert = urlItems || [];


  const langItemsInsert : SwitchLanguageType = getLanguageLinks(contentData?.pageData,RoutingConfig.locales);
// const lc = fetchLocales();
   const headersList = await headers();
  
  // Pobieramy nasz customowy nagłówek
  const localesHeader = headersList.get('x-available-locales');
  let availableLocales = null; // Domyślna wartość (Gdyby nagłówka nie było)

if (localesHeader) {
    // 2. Zamieniamy STRING na TABLICĘ
    try {
        availableLocales = JSON.parse(localesHeader); 
        // Teraz availableLocales to: ['pl', 'en', 'fr'] (Array)
    } catch (e) {
        console.error("Błąd parsowania:", e);
    }
}
  return (
    <>
    {console.log('asvstart')}
    {console.log(availableLocales)}
    {console.log('asvend')}
    {/* {console.log('lc: '+lc)}
    
     {console.log(lc)} */}
     {/* {console.log("moje Lokacje START")}
     {console.log(getCachedLocales())}
     {console.log("moje Lokacje END")} */}
        <Header menuItems={urlItemsInsert} langItems={langItemsInsert} />
      
          {children}
        
        <Footer />
      </>
  );
}
