import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import getMenuItems from "@/functions/getMenuItems";
import { fetchPageData } from "@/functions/fetchPageData";
import { getLanguageLinks } from "@/functions/getLanguageLinks";
import vars from "@/vars/vars";
import { readFromUrl } from "@/functions/readFromUrl";
import { SwitchLanguageType } from "@/types/types";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "This is Page. The - Page.",
  description: "Generated by create next app",
};

export default async function WebLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ web?: string[],
    lang: string
   }>;
}>) {

 const { web, lang } = await params;


   const pageSlug = web?.join('/') ?? 'home';
// const rfurl = readFromUrl(web, lang);
// const fullPath = `${lang}/${contentSlug}`;

const [urlItems,contentData] = await Promise.all([
//  getMenuItems(rfurl.pageLocale),
//  fetchPageData(rfurl.pageSlug, rfurl.pageLocale)
getMenuItems(lang),
 fetchPageData(pageSlug, lang)
]);
const urlItemsInsert = urlItems || [];


  const langItemsInsert : SwitchLanguageType = getLanguageLinks(contentData?.pageData);

   
  return (
    <>
        <Header menuItems={urlItemsInsert} langItems={langItemsInsert} />
      
          {children}
        
        <Footer />
      </>
  );
}
