import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import getMenuItems from "@/functions/getMenuItems";
import { getLanguageLinks } from "@/functions/getLanguageLinks";
import { SwitchLanguageType } from "@/types/types";
import { headers } from "next/headers";
import { getPageData } from "@/functions/getPageData";
import availableLocales from '../../../config/locales.json';

import vars from "@/vars/vars";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "This is Page. The - Page.",
  description: "Generated by create next app",
};

const { home } = vars.const.slug;
const { defaultLocale } = vars.const;

export default async function WebLayout({ children, params }: Readonly<{ children: React.ReactNode, params: Promise<{ web?: string[], lang: string }>}>) {
  
  const { web, lang } = await params;
  
  const pageSlug = web?.join('/') ?? home;
  // const pageSlug = web && web.length > 0 ? web.join('/') : home;
  
  const [urlItems, contentData] = await Promise.all([
    getMenuItems(lang),
    getPageData(pageSlug, lang)
  ]);
  
  const urlItemsInsert = urlItems || [];
    
  // const headersList = await headers();
  
  // const localesHeader = headersList.get('x-available-locales');
    const insertAvailableLocales = availableLocales.length > 0 ? availableLocales : [defaultLocale];

  
  // let availableLocales : string[] = [];
  
  // if (localesHeader) {
  //   try {
  //     availableLocales = JSON.parse(localesHeader);
  //   } catch (error) {
  //     console.error("Błąd parsowania:", error);
  //   }
  // }
    const langItemsInsert : SwitchLanguageType = getLanguageLinks(contentData?.pageData,insertAvailableLocales);

  return (
  <>
    <Header menuItems={urlItemsInsert} langItems={langItemsInsert} />
      {children}
    <Footer />
  </>
  )
}