import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import getMenuItems from "@/functions/getMenuItems";
import { fetchPageData } from "@/functions/fetchPageData";
import { getLanguageLinks } from "@/functions/getLanguageLinks";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "This is Page. The - Page.",
  description: "Generated by create next app",
};

export default async function WebLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ web?: string[] }>;
}>) {

  const { web } = await params;

  // const slug = web?.join("/") || "home";
  
  const contentData = await fetchPageData(web);

  const urlItems = await getMenuItems(contentData.pageLocale) || [];

  const langItems = getLanguageLinks(contentData?.pageData);

  return (
    <html lang={contentData.pageLocale}>
      <body>
        <Header menuItems={urlItems} />
      
          {children}
        
        <Footer />
      </body>
    </html>
  );
}
