import getMenuItems from "@/functions/getMenuItems";

// import './globals.css';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { fetchPageData } from "@/functions/fetchPageData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "This is Page. The - Page.",
  description: "Generated by create next app",
};

export default async function WebLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ web?: string[] }>;
}>) {

  const { web } = await params;
  const slug = web?.join("/") || "home";
  
  const contentData = await fetchPageData(slug);


  const urlItems = await getMenuItems(`http://srv-strapi:1337/api/pages?sort=pozycja:asc`);

  if (!urlItems) return null;

  return (
    <html lang={contentData?.pageData.data.locale}>
      <body>
        <Header menuItems={urlItems} />
      
          {children}
        
        <Footer />
      </body>
    </html>
  );
}
