FROM node:22-alpine

RUN apk add --no-cache \
    curl \
    vips-dev \
    build-base \
    gcc \
    autoconf \
    automake \
    libtool \
    nasm \
    python3 \
    make

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=1337

COPY ./package*.json .

# RUN npm install
RUN npm ci --omit=dev

COPY . .

RUN npm run build

EXPOSE 1337

CMD [ "npm", "start" ]