// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

import { cookies, headers } from "next/headers";
import "../globals.css";
import { ReadonlyHeaders } from "next/dist/server/web/spec-extension/adapters/headers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode,
  params: Promise<{
    lang: string
  }>
}>) {
const { lang } = await params;
// const insertLang = lang.split('-')[0];
const insertLang = lang;

  return <>
  <html lang={insertLang}>
      <body>{children}</body>
      </html>
      </>;
}
